updated pbuilderrc to include ros and jessie

diff --git a/docker/mini-launchpad/pbuilderrc b/docker/mini-launchpad/pbuilderrc
--- a/docker/mini-launchpad/pbuilderrc
+++ b/docker/mini-launchpad/pbuilderrc
@@ -8,47 +8,6 @@ if [ "$ARCH" == "" ]; then
     exit 1
 fi
 
-if [ "${ARCH}" == "armhf" ] || [ "${ARCH}" == "arm64" ]; then
-   MIRRORSITE="http://ports.ubuntu.com/ubuntu-ports/"
-   COMPONENTS="main restricted universe multiverse"
-   OTHERMIRROR="deb http://ports.ubuntu.com/ubuntu-ports/ ${DIST} main restricted universe multiverse
-   |deb http://ports.ubuntu.com/ubuntu-ports/ ${DIST}-updates main universe multiverse
-   |deb [trusted=yes] http://repos.rcn-ee.com/ubuntu/ ${DIST} main
-   |deb [trusted=yes] http://ppa.launchpad.net/kevin-demarco/scrimmage/ubuntu ${DIST} main"
-
-elif [ "${ARCH}" == "amd64" ] || [ "${ARCH}" == "i386" ]; then
-   MIRRORSITE="http://us.archive.ubuntu.com/ubuntu/"
-   COMPONENTS="main restricted universe multiverse"
-
-   OTHERMIRROR="deb [trusted=yes] http://ppa.launchpad.net/kevin-demarco/scrimmage/ubuntu ${DIST} main
-   |deb http://us.archive.ubuntu.com/ubuntu/ ${DIST}-updates main universe multiverse"
-fi
-
-if [ "$ARCH" == "armhf" ] && [ "$(dpkg --print-architecture)" != "armhf" ]; then
-    DEBOOTSTRAP="qemu-debootstrap"
-fi
-if [ "$ARCH" == "arm64" ] && [ "$(dpkg --print-architecture)" != "arm64" ]; then
-    DEBOOTSTRAP="qemu-debootstrap"
-fi
-if [ "$ARCH" == "armel" ] && [ "$(dpkg --print-architecture)" != "armel" ]; then
-    DEBOOTSTRAP="qemu-debootstrap"
-fi
-
-DEBOOTSTRAPOPTS=("${DEBOOTSTRAPOPTS[@]}" "--arch=$ARCH")
-
-# Due to bug in apt-get in qemu, need to chnage pbuilder-satisfydepends:
-# https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=816097
-PBUILDERSATISFYDEPENDSCMD=/usr/lib/pbuilder/pbuilder-satisfydepends-experimental
-
-BASETGZ="/var/cache/pbuilder/${DIST}-${ARCH}-base.tgz"
-DISTRIBUTION="$DIST"
-ARCHITECTURE="$ARCH"
-
-#OS="ubuntu"
-#NAME="$OS-$DIST-$ARCH"
-#APTCACHE="/var/cache/pbuilder/$NAME/aptcache/"
-#BUILDPLACE="/var/cache/pbuilder/build"
-
 ### Hook Directory Option: ###
 # Lifted from https://wiki.ubuntu.com/PbuilderHowto#Running_a_Shell_When_Build_Fails_.28Intro_to_Hook_Scripts.29
 # This is not necessary but provides some helpful abilities
@@ -84,11 +43,76 @@ ARCHITECTURE="$ARCH"
 
 # Check that D05depends points to the right directory
 
-# Update tarballs:
-# sudo DIST=xenial ARCH=arm64 pbuilder --update --override-config
+# If you add additional debian repositories, you need to update your
+# pbuilder tarballs:
+# (e.g., sudo DIST=xenial ARCH=arm64 pbuilder --update --override-config)
 
 # IMPORTANT DEBUGGING NOTE: If you are getting broken packages from apt
-# try logging into the chroot with sudo DIST=xenial ARCH=(whatever arch) pbuilder --login
-# Run apt-cache policy (package-name-here)
-# compare with apt-cache policy (package-name-here) outside of chroot
+# try logging into the chroot with sudo DIST=<dist> ARCH=<arch> pbuilder --login
+# Run apt-cache policy <package-name>
+# compare with apt-cache policy <package-name> outside of chroot
 # If they are different, add the missing components to OTHERMIRROR
+
+# Determine the OS being used based on the distribution name
+if [ "${DIST}" == "trusty" ] || [ "${DIST}" == "xenial" ] || [ "${DIST}" == "bionic" ]; then
+    OS="Ubuntu"
+elif [ "${DIST}" == "buster" ] || [ "${DIST}" == "jessie" ] || [ "${DIST}" == "stretch" ]; then
+    OS="Debian"
+else
+    echo "Invalid distribution: ${DIST}"
+    OS="INVALID"
+    exit 1
+fi
+
+# Set the mirror based on the OS
+if [ "$OS" == "Debian" ]; then
+    MIRRORSITE="http://ftp.debian.org/debian/"
+    COMPONENTS="main contrib non-free"
+    DEBOOTSTRAPOPTS=("${DEBOOTSTRAPOPTS[@]}"
+                     "--keyring=/usr/share/keyrings/debian-archive-keyring.gpg")
+elif [ "$OS" == "Ubuntu" ]; then
+    # Ubuntu has different servers for arm and x86
+    if [ "${ARCH}" == "armhf" ] || [ "${ARCH}" == "arm64" ]; then
+        MIRRORSITE="http://ports.ubuntu.com/ubuntu-ports/"
+        COMPONENTS="main restricted universe multiverse"
+        OTHERMIRROR="deb http://ports.ubuntu.com/ubuntu-ports/ ${DIST} main restricted universe multiverse
+                    |deb http://ports.ubuntu.com/ubuntu-ports/ ${DIST}-updates main universe multiverse
+                    |deb [trusted=yes] http://repos.rcn-ee.com/ubuntu/ ${DIST} main
+                    |deb [trusted=yes] http://ppa.launchpad.net/kevin-demarco/scrimmage/ubuntu ${DIST} main
+                    |deb [trusted=yes] http://packages.ros.org/ros/ubuntu ${DIST} main"
+    else
+        MIRRORSITE="http://us.archive.ubuntu.com/ubuntu/"
+        COMPONENTS="main restricted universe multiverse"
+
+        OTHERMIRROR="deb [trusted=yes] http://ppa.launchpad.net/kevin-demarco/scrimmage/ubuntu ${DIST} main
+                    |deb http://us.archive.ubuntu.com/ubuntu/ ${DIST}-updates main universe multiverse
+                    |deb [trusted=yes] http://packages.ros.org/ros/ubuntu ${DIST} main"
+    fi
+else
+    echo "Invalid OS: ${OS}"
+fi
+
+if [ "$ARCH" == "armhf" ] && [ "$(dpkg --print-architecture)" != "armhf" ]; then
+    DEBOOTSTRAP="qemu-debootstrap"
+fi
+if [ "$ARCH" == "arm64" ] && [ "$(dpkg --print-architecture)" != "arm64" ]; then
+    DEBOOTSTRAP="qemu-debootstrap"
+fi
+if [ "$ARCH" == "armel" ] && [ "$(dpkg --print-architecture)" != "armel" ]; then
+    DEBOOTSTRAP="qemu-debootstrap"
+fi
+
+DEBOOTSTRAPOPTS=("${DEBOOTSTRAPOPTS[@]}" "--arch=$ARCH")
+
+# Due to bug in apt-get in qemu, need to chnage pbuilder-satisfydepends:
+# https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=816097
+PBUILDERSATISFYDEPENDSCMD=/usr/lib/pbuilder/pbuilder-satisfydepends-experimental
+
+BASETGZ="/var/cache/pbuilder/${DIST}-${ARCH}-base.tgz"
+DISTRIBUTION="$DIST"
+ARCHITECTURE="$ARCH"
+
+#OS="ubuntu"
+#NAME="$OS-$DIST-$ARCH"
+#APTCACHE="/var/cache/pbuilder/$NAME/aptcache/"
+#BUILDPLACE="/var/cache/pbuilder/build"
